/*
 * AboutUs.java
 *
 * 
 */

/**
 *
 * @author  Administrator
 */
public class AboutUs extends javax.swing.JFrame {
    
    /** Creates new form AboutUs */
    public AboutUs() {
        
        initComponents();
    }
    
    /** This method is called from whithin the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABOUT US");
        setResizable(false);
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel1.setText("----ABOUT US----");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 180, 28);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel2.setText("PROJECT OF THIRD YEAR DIPLOMA ENGINEERING");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 540, 28);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel3.setText("Name:Multiplex Functioning Project");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 540, 28);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel4.setText("By:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 40, 28);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel5.setText("Rohit Jadhav");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 160, 200, 28);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel6.setText("Santosh vishwakarma");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 190, 160, 28);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel7.setText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 220, 160, 28);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel8.setText("Features:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 260, 100, 28);

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel9.setText("6:Easy To Handle.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 440, 200, 28);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel10.setText("5:User Friendly.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 410, 160, 28);

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel11.setText("4:Food Management.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 380, 220, 28);

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel12.setText("3:Employee Management.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 350, 290, 28);

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel13.setText("2:Parking Management.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 320, 230, 28);

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel14.setText("1:Ticket Booking.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 290, 190, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        AboutUs as =new AboutUs();
        as.setSize(1000,1000);
        as.setVisible(true);
        
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
}
