/*
 * Login.java
 *
 * 
 */

/**
 *
 *
 */
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.File.*;
import javax.swing.border.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.border.LineBorder;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.JTable.*;
import javax.swing.JOptionPane.*;
import java.awt.SystemTray.*;
import javax.swing.table.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import java.util.*;
import java.io.*;
import java.lang.*;

public class Login extends javax.swing.JFrame implements ActionListener
{
        Connection con;
	Statement st;
	ResultSet rs;
	PreparedStatement ps;
         Container c;

	JLabel name;
	boolean flag = true;
	JFrame fm;

	JTextField t1;
        JTextField t2;
	
	
	JPanel jPanel1 = new JPanel();
	JPanel jPanel2 = new JPanel();
	JPanel jPanel3 = new JPanel();

	JLabel l4 = new JLabel("", new ImageIcon("images/theater.jpg"), JLabel.CENTER);
    /** Creates new form Login */
    public Login() 
    {
       super("MultiPlex Login Window");
       initComponents();
        getConnection(); 
       
       c=getContentPane();
	c.setBackground(new Color(120,0,0));
        c.setLayout(null); 
		setIconImage(new ImageIcon("images/User.png").getImage());		
		setResizable(false);

		JLabel l1 = new JLabel("User Name : ");
		JLabel l2 = new JLabel("Password : ");
		JButton ok = new JButton("Ok");
		JButton clear = new JButton("Clear");
		JButton create = new JButton("Create");
		JButton exit = new JButton("Exit");

		t1 = new JTextField();
		t1.setToolTipText("ENTER USER NAME HERE ");
		
		t2 = new JPasswordField();		
		t2.setToolTipText("ENTER PASSWARD HERE ");
		

		setLayout(null);
		setSize(1024, 768);
		setBackground(new Color(176, 251, 234));		

		l1.setBounds(20, 30, 80, 20);
		l2.setBounds(20, 70, 80, 20);
		
		t1.setBounds(120, 30, 80, 20);
		t2.setBounds(120, 70, 80, 20);

		ok.setBounds(10, 20, 80, 20);
		clear.setBounds(110, 20, 80, 20);
		exit.setBounds(210, 20, 80, 20);

		jPanel1.setBounds(520, 300, 220, 120);
		jPanel2.setBounds(480, 430, 300, 60);

		//t2.setEchoChar('*');
		
		c.add(jPanel1);
		c.add(jPanel2);
		c.add(jPanel3);

		jPanel1.add(l1); jPanel1.add(l2);
		jPanel1.add(t1); jPanel1.add(t2);
		
		jPanel2.add(ok); jPanel2.add(clear); jPanel2.add(exit);

		jPanel3.add(l4);
		jPanel3.setBounds(0-10, 0-10, 1054, 778);
                jPanel3.setBackground(new Color(120,0,0));
		jPanel1.setLayout(null);
		jPanel2.setLayout(null);

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		ok.addActionListener(this);
		clear.addActionListener(this);
		create.addActionListener(this);
		exit.addActionListener(this);
		
		//Font f1 = new Font("Monotype Corsiva",Font.BOLD,30);
		//name=new JLabel("Multiplex Entertainment System...");
		//l4.add(name);
		//name.setBounds(200,100,900,90);
		//name.setFont(f1);
		//name.setForeground(new Color(255, 0, 0));

                
       Container contentPane=getContentPane();
       getContentPane().setLayout(null);
       
         setSize(1250,750);
          setVisible(true);
		
		
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 9, 9));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public void getConnection()
{
    try
				{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			con = DriverManager.getConnection("jdbc:odbc:MultiplexDSN");
                          // JOptionPane.showMessageDialog(null,"Connection Successful");
        	st=con.createStatement();

        		}
			catch(Exception ee)			{
				JOptionPane.showMessageDialog(null,ee,"Error in Connection",JOptionPane.ERROR_MESSAGE);
				}
}
    public void actionPerformed(ActionEvent a)
	{
		String s1 = a.getActionCommand();

		if (s1.equals("Exit"))
		{
			dispose();
		}
		else
		if (s1.equals("Ok"))
		{
			try
			{
				String s2 = t1.getText().trim().toLowerCase();
                                String s3 = t2.getText().trim().toLowerCase();
                                
				rs = st.executeQuery("select * from Login");

				whileloop : while (rs.next())
				{
					if (s2.equals(rs.getString("Username")))
					{												
						if (s3.equals(rs.getString("Password")))
						{
							flag = true;

							new Home();
							setVisible(false);

							break whileloop;
						}
						else
						{
							String dt = "Error Message";
							String dm = "Invalid password";
							int dtype = JOptionPane.ERROR_MESSAGE;

							JOptionPane.showMessageDialog((Component)null, dm, dt, dtype);
							t2.setText("");
							t2.requestFocus();
						}
					}
					else
					{
						flag = false;						
					}
				}

				if (flag == false)
				{
					String dt = "Error Message";
					String dm = "Invalid Login name";
					int dtype = JOptionPane.ERROR_MESSAGE;

					JOptionPane.showMessageDialog((Component)null, dm, dt, dtype);
					t1.setText("");
					t1.requestFocus();
				}
			}
			catch (Exception e)
			{
				String dt = "Error Message";
				String dm = "SQL ERROR : " + e;
				int dtype = JOptionPane.ERROR_MESSAGE;

				JOptionPane.showMessageDialog((Component)null, dm, dt, dtype);
			}
		}
		else
		{
			t1.setText("");
			t2.setText("");
			t1.requestFocus();
		}
	}
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
