
public class MovieTime extends javax.swing.JFrame {
    
    /** Creates new form MovieTime */
    public MovieTime() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tmovietimeid = new javax.swing.JTextField();
        tmdate = new javax.swing.JTextField();
        tempid = new javax.swing.JTextField();
        ttime = new javax.swing.JTextField();
        tscreenid = new javax.swing.JTextField();
        tmovieid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MovieTableDetails = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("AcadEref", 1, 12));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Movie Time Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 180, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("MovieTimeId");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 90, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setText("MovieId");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 60, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("ScreenId");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 70, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Time");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 40, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("EmpId");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 150, 60, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("ModifyDate");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 80, 15);

        getContentPane().add(tmovietimeid);
        tmovietimeid.setBounds(150, 60, 140, 20);

        getContentPane().add(tmdate);
        tmdate.setBounds(150, 210, 140, 20);

        getContentPane().add(tempid);
        tempid.setBounds(150, 150, 140, 20);

        getContentPane().add(ttime);
        ttime.setBounds(150, 180, 140, 20);

        getContentPane().add(tscreenid);
        tscreenid.setBounds(150, 120, 140, 20);

        getContentPane().add(tmovieid);
        tmovieid.setBounds(150, 90, 140, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Next");
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 100, 110, 23);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jButton2.setText("Previous");
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 130, 110, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setText("Delete");
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 160, 110, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setText("Exit");
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 250, 100, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setText("Clear");
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 190, 110, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setText("Submit");
        getContentPane().add(jButton6);
        jButton6.setBounds(320, 220, 110, 23);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton7.setText("Update");
        getContentPane().add(jButton7);
        jButton7.setBounds(320, 250, 110, 23);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton8.setText("Search");
        getContentPane().add(jButton8);
        jButton8.setBounds(320, 70, 110, 23);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton9.setText("Settime");
        getContentPane().add(jButton9);
        jButton9.setBounds(110, 250, 110, 23);

        MovieTableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MovieTimeId", "MovieId", "ScreenId", "EmpId", "Time", "Mdate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MovieTableDetails);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 490, 90);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("Movie Time Form");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 290, 180, 22);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton10.setText("SetDate");
        getContentPane().add(jButton10);
        jButton10.setBounds(220, 250, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTime().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MovieTableDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tempid;
    private javax.swing.JTextField tmdate;
    private javax.swing.JTextField tmovieid;
    private javax.swing.JTextField tmovietimeid;
    private javax.swing.JTextField tscreenid;
    private javax.swing.JTextField ttime;
    // End of variables declaration//GEN-END:variables
    
}
