
public class Multiplex extends javax.swing.JFrame {
    
    /** Creates new form Multiplex */
    public Multiplex() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu2 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        jMenuBar1 = new javax.swing.JMenuBar();

        menu1.setLabel("Menu");
        menuBar1.add(menu1);

        menu2.setLabel("Menu");
        menuBar2.add(menu2);

        menu3.setLabel("Menu");
        menuBar3.add(menu3);

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiplex().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    // End of variables declaration//GEN-END:variables
    
}
