/*
 * TicketBooking.java
 *
 * 
 */

/**
 *
 * @author  Administrator
 */
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.border.*;
import java.io.*;
import java.io.File.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.border.LineBorder;
import javax.swing.JTable.*;
import javax.swing.JOptionPane.*;
import java.awt.SystemTray.*;
import javax.swing.table.*;
import java.sql.*;
import javax.swing.*;
import java.awt.color.*;
import java.lang.*;
public class TicketBooking extends javax.swing.JFrame implements ActionListener, ItemListener
{
    
    /** Creates new form TicketBooking */
    
     Container c;
     JFrame fm;
     JComboBox cmbMovie,cmbScreen,cmbTime;
     
      Connection con;
    ResultSet rs;
     PreparedStatement ps;
    Statement st;
    Boolean insertFlag ; //For Save button to Insert or Update Records
     String btnbook;
     
     int ticketAmt;
    public TicketBooking() {
        initComponents();
        getConnection();
        c=getContentPane();
	c.setBackground(new Color(70,255,10));
	c.setLayout(null);
        AllActionListener();
        
        cmbMovie = new JComboBox();
        cmbScreen = new JComboBox();
        cmbTime = new JComboBox();
        c.add(cmbMovie);
        c.add(cmbScreen);
        c.add(cmbTime);
        //cmbMovie.addActionListener(this);
        //cmbScreen.addActionListener(this);
        //cmbTime.addActionListener(this);
        //cmbMovie.addItemListener(this);
       // cmbScreen.addItemListener(this);
         cmbTime.addItemListener(this);
         cmbMovie.setBounds(380,140,130,20);
         cmbScreen.setBounds(700,140,130,20);
         cmbTime.setBounds(970,140,130,20);
         bindMovieCombo(); 
         bindScreenCombo();
         bindTimeCombo();
         bindTicketButton();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        Bnext10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        Bprint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tempvtype = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        Bbook = new javax.swing.JButton();
        Bhome = new javax.swing.JButton();
        Bcolor = new javax.swing.JButton();
        Bcancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Fame - Multiplex Cinema , NASIK");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Select Movie  :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Select Screen : ");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Show Time  :");

        A1.setBackground(new java.awt.Color(255, 204, 0));
        A1.setFont(new java.awt.Font("Arial", 1, 12));
        A1.setText("A1");
        A1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A2.setBackground(new java.awt.Color(255, 204, 0));
        A2.setFont(new java.awt.Font("Arial", 1, 12));
        A2.setText("A2");
        A2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A3.setBackground(new java.awt.Color(255, 204, 0));
        A3.setFont(new java.awt.Font("Arial", 1, 12));
        A3.setText("A3");
        A3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 0), null, null));

        A4.setBackground(new java.awt.Color(255, 204, 0));
        A4.setFont(new java.awt.Font("Arial", 1, 12));
        A4.setText("A4");
        A4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A5.setBackground(new java.awt.Color(255, 204, 0));
        A5.setFont(new java.awt.Font("Arial", 1, 12));
        A5.setText("A5");
        A5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A6.setBackground(new java.awt.Color(255, 204, 0));
        A6.setFont(new java.awt.Font("Arial", 1, 12));
        A6.setText("A6");
        A6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A7.setBackground(new java.awt.Color(255, 204, 0));
        A7.setFont(new java.awt.Font("Arial", 1, 12));
        A7.setText("A7");
        A7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A8.setBackground(new java.awt.Color(255, 204, 0));
        A8.setFont(new java.awt.Font("Arial", 1, 12));
        A8.setText("A8");
        A8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A9.setBackground(new java.awt.Color(255, 204, 0));
        A9.setFont(new java.awt.Font("Arial", 1, 12));
        A9.setText("A9");
        A9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        A10.setBackground(new java.awt.Color(255, 204, 0));
        A10.setFont(new java.awt.Font("Arial", 1, 12));
        A10.setText("A10");
        A10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Bnext10.setBackground(new java.awt.Color(255, 0, 0));
        Bnext10.setFont(new java.awt.Font("Arial", 1, 12));
        Bnext10.setText("Current Booking Status");
        Bnext10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Golden Seats Rs 200");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Silver Seats Rs 150");

        B1.setFont(new java.awt.Font("Arial", 1, 12));
        B1.setText("B1");
        B1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B2.setFont(new java.awt.Font("Arial", 1, 12));
        B2.setText("B2");
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B3.setFont(new java.awt.Font("Arial", 1, 12));
        B3.setText("B3");
        B3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B4.setFont(new java.awt.Font("Arial", 1, 12));
        B4.setText("B4");
        B4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B5.setFont(new java.awt.Font("Arial", 1, 12));
        B5.setText("B5");
        B5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B6.setFont(new java.awt.Font("Arial", 1, 12));
        B6.setText("B6");
        B6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B7.setFont(new java.awt.Font("Arial", 1, 12));
        B7.setText("B7");
        B7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B8.setFont(new java.awt.Font("Arial", 1, 12));
        B8.setText("B8");
        B8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B9.setFont(new java.awt.Font("Arial", 1, 12));
        B9.setText("B9");
        B9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B10.setFont(new java.awt.Font("Arial", 1, 12));
        B10.setText("B10");
        B10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Platinum Seats Rs 100");

        C1.setBackground(new java.awt.Color(0, 153, 153));
        C1.setFont(new java.awt.Font("Arial", 1, 12));
        C1.setText("C1");
        C1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C2.setBackground(new java.awt.Color(0, 153, 153));
        C2.setFont(new java.awt.Font("Arial", 1, 12));
        C2.setText("C2");
        C2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C3.setBackground(new java.awt.Color(0, 153, 153));
        C3.setFont(new java.awt.Font("Arial", 1, 12));
        C3.setText("C3");
        C3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C4.setBackground(new java.awt.Color(0, 153, 153));
        C4.setFont(new java.awt.Font("Arial", 1, 12));
        C4.setText("C4");
        C4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C5.setBackground(new java.awt.Color(0, 153, 153));
        C5.setFont(new java.awt.Font("Arial", 1, 12));
        C5.setText("C5");
        C5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C6.setBackground(new java.awt.Color(0, 153, 153));
        C6.setFont(new java.awt.Font("Arial", 1, 12));
        C6.setText("C6");
        C6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C7.setBackground(new java.awt.Color(0, 153, 153));
        C7.setFont(new java.awt.Font("Arial", 1, 12));
        C7.setText("C7");
        C7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C8.setBackground(new java.awt.Color(0, 153, 153));
        C8.setFont(new java.awt.Font("Arial", 1, 12));
        C8.setText("C8");
        C8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C9.setBackground(new java.awt.Color(0, 153, 153));
        C9.setFont(new java.awt.Font("Arial", 1, 12));
        C9.setText("C9");
        C9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        C10.setBackground(new java.awt.Color(0, 153, 153));
        C10.setFont(new java.awt.Font("Arial", 1, 12));
        C10.setText("C10");
        C10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Bprint.setFont(new java.awt.Font("Arial", 1, 12));
        Bprint.setText("Print");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel6.setForeground(new java.awt.Color(236, 233, 216));
        jLabel6.setText("Ticket Booking Id :");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Movie Date  :");

        tempvtype.setBackground(new java.awt.Color(236, 233, 216));
        tempvtype.setBorder(null);

        Bbook.setFont(new java.awt.Font("Arial", 1, 12));
        Bbook.setText("Book ");

        Bhome.setFont(new java.awt.Font("Arial", 1, 12));
        Bhome.setText("Home");

        Bcolor.setFont(new java.awt.Font("Arial", 1, 12));
        Bcolor.setText("Color");

        Bcancle.setFont(new java.awt.Font("Arial", 1, 12));
        Bcancle.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(568, 568, 568)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(C1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(B1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(A1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(80, 80, 80)
                                                        .addComponent(Bnext10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(A7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(A8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(A9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(A10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                    .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bbook, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bcancle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(tempvtype, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(tempvtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(76, 76, 76)
                .addComponent(Bnext10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bbook)
                    .addComponent(Bprint)
                    .addComponent(Bcancle)
                    .addComponent(Bhome)
                    .addComponent(Bcolor))
                .addGap(103, 103, 103))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public void getConnection()
{
    try
				{
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			con = DriverManager.getConnection("jdbc:odbc:MultiplexDSN");
                          // JOptionPane.showMessageDialog(null,"Connection Successful");
        	st=con.createStatement();

        		}
			catch(Exception ee)			{
				JOptionPane.showMessageDialog(null,ee,"Error in Connection",JOptionPane.ERROR_MESSAGE);
				}
}
    public void AllActionListener()
    {
        Bcolor.addActionListener(this);
        Bbook.addActionListener(this);
        Bprint.addActionListener(this);
        Bcancle.addActionListener(this);
        Bhome.addActionListener(this);
        Bnext10.addActionListener(this);
        A1.addActionListener(this);
        A2.addActionListener(this);
        A3.addActionListener(this);
        A4.addActionListener(this);
        A5.addActionListener(this);
        A6.addActionListener(this);
        A7.addActionListener(this);
        A8.addActionListener(this);
        A9.addActionListener(this);
        A10.addActionListener(this);
        B1.addActionListener(this);
        B2.addActionListener(this);
        B3.addActionListener(this);
        B4.addActionListener(this);
        B5.addActionListener(this);
        B6.addActionListener(this);
        B7.addActionListener(this);
        B8.addActionListener(this);
        B9.addActionListener(this);
        B10.addActionListener(this);
        C1.addActionListener(this);
        C2.addActionListener(this);
        C3.addActionListener(this);
        C4.addActionListener(this);
        C5.addActionListener(this);
        C6.addActionListener(this);
        C7.addActionListener(this);
        C8.addActionListener(this);
        C9.addActionListener(this);
        C10.addActionListener(this);
  
    }
    public void bindMovieCombo()
{ 
     
     //Binding    Movie Combo
    
    try
        {
            //ps = con.prepareStatement("select * from Employee");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("Select * From Movie");

            boolean found = false;
            rs.beforeFirst();
            while(rs.next())
            {
                    found = true;
                    cmbMovie.addItem(rs.getString("MovieName"));
            }
            rs.first();
        } 
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(this,"My Error is : "+e);
        }
 		
}
     public void bindScreenCombo()
{ 
     
     //Binding    Screen Combo
    
    try
        {
            //ps = con.prepareStatement("select * from Employee");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("Select * From Screen");

            boolean found = false;
            rs.beforeFirst();
            while(rs.next())
            {
                    found = true;
                    cmbScreen.addItem(rs.getString("ScreenName"));
            }
            rs.first();
        } 
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(this,"My Error is : "+e);
        }
 		
}
     
     public void bindTimeCombo()
     {
          // Binding    Screen Combo
    
        try
        {
            //ps = con.prepareStatement("select * from Employee");
            st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("Select * From MovieTime");

            boolean found = false;
            rs.beforeFirst();
            while(rs.next())
            {
                    found = true;
                    cmbTime.addItem(rs.getString("Time"));
            }
            rs.first();
         } 
          catch(Exception e)
        {
                JOptionPane.showMessageDialog(this,"My Error is : "+e);
        }
     }
     
     public void bindTicketButton()
     {
        String time ;
       
        //Set the Default Color After Booking 
        
        A1.setBackground(new Color(255,204,0));
        A2.setBackground(new Color(255,204,0));
        A3.setBackground(new Color(255,204,0));
        A4.setBackground(new Color(255,204,0));
        A5.setBackground(new Color(255,204,0));
        A6.setBackground(new Color(255,204,0));
        A7.setBackground(new Color(255,204,0));
        A8.setBackground(new Color(255,204,0));
        A9.setBackground(new Color(255,204,0));
        A10.setBackground(new Color(255,204,0));
        
        B1.setBackground(new Color(236,233,216));
        B2.setBackground(new Color(236,233,216));
        B3.setBackground(new Color(236,233,216));
        B4.setBackground(new Color(236,233,216));
        B5.setBackground(new Color(236,233,216));
        B6.setBackground(new Color(236,233,216));
        B7.setBackground(new Color(236,233,216));
        B8.setBackground(new Color(236,233,216));
        B9.setBackground(new Color(236,233,216));
        B10.setBackground(new Color(236,233,216));
        
        C1.setBackground(new Color(0,153,153));
        C2.setBackground(new Color(0,153,153));
        C3.setBackground(new Color(0,153,153));
        C4.setBackground(new Color(0,153,153));
        C5.setBackground(new Color(0,153,153));
        C6.setBackground(new Color(0,153,153));
        C7.setBackground(new Color(0,153,153));
        C8.setBackground(new Color(0,153,153));
        C9.setBackground(new Color(0,153,153));
        C10.setBackground(new Color(0,153,153));
        

        int cnt=0;
        try
      {
	time = cmbTime.getSelectedItem().toString();
               
        //JOptionPane.showMessageDialog(this,"This is in bindTicketbutton " + time);
        ps = con.prepareStatement("SELECT * FROM MovieTime INNER JOIN SeatBook ON MovieTime.TimeId=SeatBook.TimeId WHERE MovieTime.Time=?");
        ps.setString(1,time);
        rs = ps.executeQuery();
           
        while (rs.next())
        {
            cnt=cnt+1;
            String Available = rs.getString("SAvailable");
             String seatid = rs.getString("SeatId");
            //JOptionPane.showMessageDialog(this,Available);
            if(Available.equals("1"))
            {
                      
               
                if(seatid.equals("1"))
                {
                    A1.setEnabled(false);
                   
                }
                if(seatid.equals("2"))
                {
                    A2.setEnabled(false);
                }
                 if(seatid.equals("3"))
                {
                    A3.setEnabled(false);
                }
                 if(seatid.equals("4"))
                {
                    A4.setEnabled(false);
                }
                 if(seatid.equals("5"))
                {
                    A5.setEnabled(false);
                }
                 if(seatid.equals("6"))
                {
                    A6.setEnabled(false);
                }
                 if(seatid.equals("7"))
                {
                    A7.setEnabled(false);
                }
                 if(seatid.equals("8"))
                {
                    A8.setEnabled(false);
                }
                if(seatid.equals("9"))
                {
                    A9.setEnabled(false);
                }
                if(seatid.equals("10"))
                {
                    A10.setEnabled(false);
                }
                 if(seatid.equals("11"))
                {
                    B1.setEnabled(false);
                }
                 if(seatid.equals("12"))
                {
                    B2.setEnabled(false);
                }
                 if(seatid.equals("13"))
                {
                    B3.setEnabled(false);
                }
                 if(seatid.equals("14"))
                {
                    B4.setEnabled(false);
                }
                 if(seatid.equals("15"))
                {
                    B5.setEnabled(false);
                }
                 if(seatid.equals("16"))
                {
                    B6.setEnabled(false);
                }
                 if(seatid.equals("17"))
                {
                    B7.setEnabled(false);
                }
                 if(seatid.equals("18"))
                {
                    B8.setEnabled(false);
                }
                 if(seatid.equals("19"))
                {
                    B9.setEnabled(false);
                } if(seatid.equals("20"))
                {
                    B10.setEnabled(false);
                }
                 if(seatid.equals("21"))
                {
                    C1.setEnabled(false);
                }
                 if(seatid.equals("22"))
                {
                    C2.setEnabled(false);
                }
                 if(seatid.equals("23"))
                {
                    C3.setEnabled(false);
                }
                 if(seatid.equals("24"))
                {
                    C4.setEnabled(false);
                }
                 if(seatid.equals("25"))
                {
                    C5.setEnabled(false);
                }
                 if(seatid.equals("26"))
                {
                    C6.setEnabled(false);
                }
                 if(seatid.equals("27"))
                {
                    C7.setEnabled(false);
                }
                 if(seatid.equals("28"))
                {
                    C8.setEnabled(false);
                }
                 if(seatid.equals("29"))
                {
                    C9.setEnabled(false);
                }
                 if(seatid.equals("30"))
                {
                    C10.setEnabled(false);
                }
                 if(seatid.equals("31"))
                {
                    A1.setEnabled(false);
                   
                }
                if(seatid.equals("32"))
                {
                    A2.setEnabled(false);
                }
                 if(seatid.equals("33"))
                {
                    A3.setEnabled(false);
                }
                 if(seatid.equals("34"))
                {
                    A4.setEnabled(false);
                }
                 if(seatid.equals("35"))
                {
                    A5.setEnabled(false);
                }
                 if(seatid.equals("36"))
                {
                    A6.setEnabled(false);
                }
                 if(seatid.equals("37"))
                {
                    A7.setEnabled(false);
                }
                 if(seatid.equals("38"))
                {
                    A8.setEnabled(false);
                }
                if(seatid.equals("39"))
                {
                    A9.setEnabled(false);
                }
                if(seatid.equals("40"))
                {
                    A10.setEnabled(false);
                }
                 if(seatid.equals("41"))
                {
                    B1.setEnabled(false);
                }
                 if(seatid.equals("42"))
                {
                    B2.setEnabled(false);
                }
                 if(seatid.equals("43"))
                {
                    B3.setEnabled(false);
                }
                 if(seatid.equals("44"))
                {
                    B4.setEnabled(false);
                }
                 if(seatid.equals("45"))
                {
                    B5.setEnabled(false);
                }
                 if(seatid.equals("46"))
                {
                    B6.setEnabled(false);
                }
                 if(seatid.equals("47"))
                {
                    B7.setEnabled(false);
                }
                 if(seatid.equals("48"))
                {
                    B8.setEnabled(false);
                }
                 if(seatid.equals("49"))
                {
                    B9.setEnabled(false);
                } if(seatid.equals("50"))
                {
                    B10.setEnabled(false);
                }
                 if(seatid.equals("51"))
                {
                    C1.setEnabled(false);
                }
                 if(seatid.equals("52"))
                {
                    C2.setEnabled(false);
                }
                 if(seatid.equals("53"))
                {
                    C3.setEnabled(false);
                }
                 if(seatid.equals("54"))
                {
                    C4.setEnabled(false);
                }
                 if(seatid.equals("55"))
                {
                    C5.setEnabled(false);
                }
                 if(seatid.equals("56"))
                {
                    C6.setEnabled(false);
                }
                 if(seatid.equals("57"))
                {
                    C7.setEnabled(false);
                }
                 if(seatid.equals("58"))
                {
                    C8.setEnabled(false);
                }
                 if(seatid.equals("59"))
                {
                    C9.setEnabled(false);
                }
                 if(seatid.equals("60"))
                {
                    C10.setEnabled(false);
                }
  
            }
            else
            {
                 if(seatid.equals("1"))
                {
                    A1.setEnabled(true);
                   // JOptionPane.showMessageDialog(this,"A1 Ticket  Available");
                }
                
                if(seatid.equals("2"))
                {
                    A2.setEnabled(true);
                }
                 if(seatid.equals("3"))
                {
                    A3.setEnabled(true);
                }
                 if(seatid.equals("4"))
                {
                    A4.setEnabled(true);
                }
                 if(seatid.equals("5"))
                {
                    A5.setEnabled(true);
                }
                 if(seatid.equals("6"))
                {
                    A6.setEnabled(true);
                }
                 if(seatid.equals("7"))
                {
                    A7.setEnabled(true);
                }
                 if(seatid.equals("8"))
                {
                    A8.setEnabled(true);
                }
                if(seatid.equals("9"))
                {
                    A9.setEnabled(true);
                }
                if(seatid.equals("10"))
                {
                    A10.setEnabled(true);
                } 
                if(seatid.equals("11"))
                {
                    B1.setEnabled(true);
                }
                 if(seatid.equals("12"))
                {
                    B2.setEnabled(true);
                }
                 if(seatid.equals("13"))
                {
                    B3.setEnabled(true);
                }
                 if(seatid.equals("14"))
                {
                    B4.setEnabled(true);
                }
                 if(seatid.equals("15"))
                {
                    B5.setEnabled(true);
                }
                 if(seatid.equals("16"))
                {
                    B6.setEnabled(true);
                }
                 if(seatid.equals("17"))
                {
                    B7.setEnabled(true);
                }
                 if(seatid.equals("18"))
                {
                    B8.setEnabled(true);
                }
                 if(seatid.equals("19"))
                {
                    B9.setEnabled(true);
                } if(seatid.equals("20"))
                {
                    B10.setEnabled(true);
                }
                 if(seatid.equals("21"))
                {
                    C1.setEnabled(true);
                }
                 if(seatid.equals("22"))
                {
                    C2.setEnabled(true);
                }
                 if(seatid.equals("23"))
                {
                    C3.setEnabled(true);
                }
                 if(seatid.equals("24"))
                {
                    C4.setEnabled(true);
                }
                 if(seatid.equals("25"))
                {
                    C5.setEnabled(true);
                }
                 if(seatid.equals("26"))
                {
                    C6.setEnabled(true);
                }
                 if(seatid.equals("27"))
                {
                    C7.setEnabled(true);
                }
                 if(seatid.equals("28"))
                {
                    C8.setEnabled(true);
                }
                 if(seatid.equals("29"))
                {
                    C9.setEnabled(true);
                }
                 if(seatid.equals("30"))
                {
                    C10.setEnabled(true);
                } 
                if(seatid.equals("31"))
                {
                    A1.setEnabled(true);
                   
                }
                if(seatid.equals("32"))
                {
                    A2.setEnabled(true);
                }
                 if(seatid.equals("33"))
                {
                    A3.setEnabled(true);
                }
                 if(seatid.equals("34"))
                {
                    A4.setEnabled(true);
                }
                 if(seatid.equals("35"))
                {
                    A5.setEnabled(true);
                }
                 if(seatid.equals("36"))
                {
                    A6.setEnabled(true);
                }
                 if(seatid.equals("37"))
                {
                    A7.setEnabled(true);
                }
                 if(seatid.equals("38"))
                {
                    A8.setEnabled(true);
                }
                if(seatid.equals("39"))
                {
                    A9.setEnabled(true);
                }
                if(seatid.equals("40"))
                {
                    A10.setEnabled(true);
                }
                 if(seatid.equals("41"))
                {
                    B1.setEnabled(true);
                }
                 if(seatid.equals("42"))
                {
                    B2.setEnabled(true);
                }
                 if(seatid.equals("43"))
                {
                    B3.setEnabled(true);
                }
                 if(seatid.equals("44"))
                {
                    B4.setEnabled(true);
                }
                 if(seatid.equals("45"))
                {
                    B5.setEnabled(true);
                }
                 if(seatid.equals("46"))
                {
                    B6.setEnabled(true);
                }
                 if(seatid.equals("47"))
                {
                    B7.setEnabled(true);
                }
                 if(seatid.equals("48"))
                {
                    B8.setEnabled(true);
                }
                 if(seatid.equals("49"))
                {
                    B9.setEnabled(true);
                } if(seatid.equals("50"))
                {
                    B10.setEnabled(true);
                }
                 if(seatid.equals("51"))
                {
                    C1.setEnabled(true);
                }
                 if(seatid.equals("52"))
                {
                    C2.setEnabled(true);
                }
                 if(seatid.equals("53"))
                {
                    C3.setEnabled(true);
                }
                 if(seatid.equals("54"))
                {
                    C4.setEnabled(true);
                }
                 if(seatid.equals("55"))
                {
                    C5.setEnabled(true);
                }
                 if(seatid.equals("56"))
                {
                    C6.setEnabled(true);
                }
                 if(seatid.equals("57"))
                {
                    C7.setEnabled(true);
                }
                 if(seatid.equals("58"))
                {
                    C8.setEnabled(true);
                }
                 if(seatid.equals("59"))
                {
                    C9.setEnabled(true);
                }
                 if(seatid.equals("60"))
                {
                    C10.setEnabled(true);
                }
              
            }
        
         }
      }
    catch(Exception e)
   {
      JOptionPane.showMessageDialog(this,"Error is : "+e);
   }
     }
     public void actionPerformed(ActionEvent ae)
     {
         
         
         if(ae.getSource()==Bcolor)
              		{
			Color clr=JColorChooser.showDialog(fm,"RDBS",Color.red);
			c.setBackground(clr);
		}
         if(ae.getSource()==Bhome)
         {
             dispose();
             new Home();
         }
         if(ae.getSource()==Bnext10)
         {
             bindTicketButton();
         }
         if(ae.getSource()==Bprint)
         {
             String Mname = cmbMovie.getSelectedItem().toString();
             String Mdate = txtDate.getText();
             String Mtime = cmbTime.getSelectedItem().toString();
             String Mscreen = cmbScreen.getSelectedItem().toString();
             String Seatno = btnbook;
             String Amount =Integer.toString(ticketAmt);
             dispose();
             new Ticketprint(Mname,Mdate,Mtime,Mscreen,Seatno,Amount).setVisible(true);
         }
         if(ae.getSource()==A1)
         {
            btnbook="A1";
            A1.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A2)
         {
            btnbook="A2";
            A2.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A3)
         {
            btnbook="A3";
            A3.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A4)
         {
            btnbook="A4";
            A4.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A5)
         {
            btnbook="A5";
            A5.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A6)
         {
            btnbook="A6";
            A6.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A7)
         {
            btnbook="A7";
            A7.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A8)
         {
            btnbook="A8";
            A8.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A9)
         {
            btnbook="A9";
            A9.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==A10)
         {
            btnbook="A10";
            A10.setBackground(Color.RED);
            ticketAmt=200;
         }
         if(ae.getSource()==B1)
         {
            btnbook="B1";
            B1.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B2)
         {
            btnbook="B2";
            B2.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B3)
         {
            btnbook="B3";
             B3.setBackground(Color.RED);
             ticketAmt=150;
         }
         if(ae.getSource()==B4)
         {
            btnbook="B4";
            B4.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B5)
         {
            btnbook="B5";
            B5.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B6)
         {
            btnbook="B6";
            B6.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B7)
         {
            btnbook="B7";
            B7.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B8)
         {
            btnbook="B8";
            B8.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B9)
         {
            btnbook="B9";
            B9.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==B10)
         {
            btnbook="B10";
            B10.setBackground(Color.RED);
            ticketAmt=150;
         }
         if(ae.getSource()==C1)
         {
            btnbook="C1";
            C1.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C2)
         {
            btnbook="C2";
            C2.setBackground(Color.RED);
            ticketAmt=100;
         }
         if(ae.getSource()==C3)
         {
            btnbook="C3";
            C3.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C4)
         {
            btnbook="C4";
            C4.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C5)
         {
            btnbook="C5";
            C5.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C6)
         {
            btnbook="C6";
            C6.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C7)
         {
            btnbook="C7";
            C7.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C8)
         {
            btnbook="C8";
            C8.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C9)
         {
            btnbook="C9";
            C9.setBackground(Color.RED);
             ticketAmt=100;
         }
         if(ae.getSource()==C10)
         {
            btnbook="C10";
            C10.setBackground(Color.RED);
             ticketAmt=100;
         }
         
         
         if(ae.getSource()==Bbook)
         {
            try
            {
             ps=con.prepareStatement("UPDATE SeatBook INNER JOIN MovieTime ON SeatBook.TimeId = MovieTime.TimeId SET SeatBook.SAvailable = 1 WHERE SeatBook.SeatNo=? AND MovieTime.Time=?");
             ps.setString(1,btnbook);
             String time = cmbTime.getSelectedItem().toString();
             ps.setString(2,time);
             ps.executeUpdate();
             //JOptionPane.showMessageDialog(this,"Time :" + time);
              JOptionPane.showMessageDialog(this,"Ticket No : "+ btnbook + " Booked Successfully");
             // dispose();
             // new TicketBooking().setVisible(true);
              bindTicketButton();         
            }
            catch(Exception e)
           {
                JOptionPane.showMessageDialog(this,"My Error is : "+e);
           }
         }
     }
     
     public void itemStateChanged(ItemEvent ie)
     {
         String s = (String)ie.getItem();
         /*
         if(s.equals("Golmal"))
         {
         JOptionPane.showMessageDialog(this,s);
         }
         JOptionPane.showMessageDialog(this,"Any Combo Click");
          */
         //bindTicketButton();
         //JOptionPane.showMessageDialog(this,s);
     }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Bbook;
    private javax.swing.JButton Bcancle;
    private javax.swing.JButton Bcolor;
    private javax.swing.JButton Bhome;
    private javax.swing.JButton Bnext10;
    private javax.swing.JButton Bprint;
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tempvtype;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
    
}
